// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi demo.
This is a demo server for exercise 2.


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - text/plain

    Produces:
    - application/octet-stream

swagger:meta
*/
package restapi
