// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewPostBase64DecodeParams creates a new PostBase64DecodeParams object
// no default values defined in spec.
func NewPostBase64DecodeParams() PostBase64DecodeParams {

	return PostBase64DecodeParams{}
}

// PostBase64DecodeParams contains all the bound params for the post base64 decode operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostBase64Decode
type PostBase64DecodeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*base64 encoded string
	  Required: true
	  In: body
	*/
	Base64String string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostBase64DecodeParams() beforehand.
func (o *PostBase64DecodeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("base64String", "body", ""))
			} else {
				res = append(res, errors.NewParseError("base64String", "body", "", err))
			}
		} else {
			// no validation required on inline body
			o.Base64String = body
		}
	} else {
		res = append(res, errors.Required("base64String", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
